# Generated by Django 4.0.3 on 2022-05-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, verbose_name='Kurs nomi')),
                ('count_module', models.IntegerField(verbose_name='Modullar soni')),
                ('image', models.ImageField(upload_to='course_img/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
