# Generated by Django 4.0.3 on 2022-05-17 01:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Sarlavha')),
                ('img', models.ImageField(upload_to='blog_img/', verbose_name='Rasm')),
                ('description', models.TextField(verbose_name='Matn')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('like', models.IntegerField(default=0, verbose_name='Like')),
                ('dislike', models.IntegerField(default=0, verbose_name='Dislike')),
                ('popular', models.IntegerField(default=0, verbose_name="Ko'rilganlar soni")),
                ('category_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category_blog')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
